rules:
  - id: android-network-security-config-present
    languages:
      - xml
    message: "A network security profile has been detected. Please ensure that all network security related settings are configured correctly as required by the custom or newly added CA in your project."
    metadata:
      category: android.security
    paths:
      include:
        - res/xml/network_security_config.xml 
    pattern-either:
      - pattern: <network-security-config ...>$CONFIG</network-security-config>
      - pattern: <network-security-config .../>
      - pattern: <network-security-config ...></network-security-config>
    severity: INFO