rules:
  - id: android-cleartext-traffic-domain-config
    languages:
      - xml
    message: Cleartext traffic is permitted for specific domains. Verify this is intentional and secure.
    severity: WARNING
    paths:
      include:
        - '*.xml'
    pattern: |
      <domain-config cleartextTrafficPermitted="true">
          <domain>...</domain>
      </domain-config>