rules:
  - id: android-default-config-api-level-24-to-27
    languages:
      - xml
    message: "Default configuration for API level 24 to 27 detected. Cleartext traffic is permitted by default."
    severity: WARNING
    paths:
      include:
        - "*.xml"
    pattern-regex: (?s)<base-config\s+cleartextTrafficPermitted="true".*?<trust-anchors>.*?<certificates\s+src="system"\s*/>.*?</trust-anchors>.*?</base-config>