rules:
  - id: android-network-security-config-location
    languages:
      - xml
    message: Network Security Configuration is defined. Ensure the configuration file is properly set up.
    paths:
      include:
        - "AndroidManifest.xml"
    pattern: '<application ... android:networkSecurityConfig="@xml/network_security_config" ...>'
    severity: ERROR