rules:
  - id: cleartext-communication-network-config-domain
    languages:
      - xml
    message: >
      Cleartext traffic is permitted in the network security configuration. This
      can expose sensitive data to network attacks.
    paths:
      include:
        - '**/*.xml'
    patterns:
      - pattern: |
          <domain-config cleartextTrafficPermitted="true">
            ...
          </domain-config>
      - pattern-not: |
          <domain-config cleartextTrafficPermitted="false">
            ...
          </domain-config>
    severity: WARNING
    metadata:
      references:
        - https://developer.android.com/training/articles/security-config#CleartextTraffic
      category: security
      confidence: MEDIUM
    options:
      xml:
        allow_multiline: true
