rules:
- fix: 'Ensure ''cleartextTrafficPermitted'' is set to ''false'' and use system certificates
    for trust anchors.

    '
  id: insecure-network-security-config
  languages:
  - xml
  message: Insecure network security configuration detected. Ensure secure connections
    are enforced.
  metadata:
    category: security
    technology: android
  pattern-not-inside:
  - pattern: '<domain-config cleartextTrafficPermitted="false" />

      '
  - pattern: "<trust-anchors>\n  <certificates src=\"system\" />\n"
  patterns:
  - pattern: "<network-security-config>\n  <domain-config cleartextTrafficPermitted=\"\
      true\" />\n"
  - pattern: "<network-security-config>\n  <domain-config>\n    <trust-anchors>\n\
      \      <certificates src=\"user\" />\n    </trust-anchors>\n  </domain-config>\n\
      </network-security-config>\n"
  severity: ERROR
