RC_SUPPORT=false
APP_PHASE=RELEASE
TALK_SERVER_PROTOCOL_SSL=https
TALK_SERVER_PROTOCOL=http
TALK_SERVER_HOST=ga2.line.naver.jp
TALK_SERVER_HOST_SECONDARY=ga2k.line.naver.jp
TALK_SERVER_HOST_VIETNAM=ga2v.line.naver.jp
TALK_SERVER_HOST_INDONESIA=ga2s.line.naver.jp
LEGY_SPDY_PORT1=443
LEGY_SPDY_PORT2=443
LEGY_SPDY_PORT3=443
LEGY_SPDY_SSL_PORT1=443
LEGY_SPDY_SSL_PORT2=443
LEGY_SPDY_SSL_PORT3=443
OBJECT_STORAGE_SERVER_HOST=os.line.naver.jp
OBS_CDN_SERVER_HOST=dl.os.line.naver.jp
URL_SHOP_CDN_SERVER_HOST=dl.shop.line.naver.jp
URL_CONTACT_US=http://line-web.naver.jp/cs/
URL_PATTERN_CONTACT_US=(http|https)://(line-web[.]naver[.]jp/cs/|contact[.]line[.]me/).*
URL_PREFIX_TOS=http://line-web.naver.jp/app/terms/
URL_PREFIX_PRIVACY=http://line-web.naver.jp/app/line_rules/
URL_PREFIX_NAVERKR_PRIVACY=http://terms.line.me/line_terms_privacy/sp?lang=
URL_PREFIX_NAVERKR_TOS=http://terms.line.me/line_terms/sp?lang=
URL_PREFIX_360_PRIVACY=http://www.lianwo8.com/rules.html
URL_PREFIX_360_TOS=http://www.lianwo8.com/terms.html
APPLICATION_TYPE=ANDROID
#SEND_TASK_INTERVAL_CHATING=20 // 20 sec
SEND_TASK_INTERVAL_CHATING=20
#SEND_TASK_INTERVAL_NORMAL=30 * 60 // 30 min
SEND_TASK_INTERVAL_NORMAL=1800
#LOCAL_CONTACT_SYNC_INTERVAL_IN_SLEEP=5 * 60 * 60 * 1000 // 5 hours
LOCAL_CONTACT_SYNC_INTERVAL_IN_SLEEP=18000000
#ACCESS_TOKEN_REFRESH_INTERVAL=24 * 60 * 60 * 1000 // 24h
ACCESS_TOKEN_REFRESH_INTERVAL=86400000
#NEW_CONTACT_DURATION_TIME=3 * 60 * 1000 // 3min
NEW_CONTACT_DURATION_TIME=180000
#MORE_ITEM_BADGE_MAX_DURATION_TIME 7days
MORE_ITEM_BADGE_MAX_DURATION_TIME=604800000
#THEME_VALIDATION_INTERVAL 24h
THEME_VALIDATION_INTERVAL=86400000
#THEME_VALIDATION_RETRY_AFTER 3h
THEME_VALIDATION_RETRY_AFTER=10800000
# THEME_SYNC_INTERVAL 24h
THEME_SYNC_INTERVAL=86400000
# THEME_SYNC_RETRY_AFTER 6h
THEME_SYNC_RETRY_AFTER=21600000
isDebug=false
virtualPurchase=false
URL_TALKSKIN_REPO=http://dl.appresource.line.naver.jp/skin/android/
URL_TALKSKIN_INDEX=http://dl.appresource.line.naver.jp/skin/skinlist_android
URL_REGISTRATION_ACCOUNT_KEY=https://t.line.naver.jp/authct/v1/keys/
URL_STICKER_SHOP_CONTENTS=http://dl.stickershop.line.naver.jp
URL_CHANNEL_ONETIME_TOKEN_FOR_VIDEO=tauth.line.naver.jp
URL_HELP=http://line-web.naver.jp/help/
URL_PREFIX_MORE=http://appresources.line.naver.jp/moretab/
MORE_TAB_API_VERSION=3
URL_MORE_TAB=list.json?lang=$LANG&region=$REGION&device=android&v=
URL_HELP_AUTH=http://line-web.naver.jp/app/authhelp/
LINE_SCHEME_SERVICE_BASE_URL_OLD=http://line.naver.jp/
APP2APP_AUTH_URL=https://channel.line.naver.jp/dialog/allow?
URL_COIN_SETTLEMENT=http://line-web.naver.jp/app/android/settlement/ja/
URL_COIN_EBIZ_RULES=http://line-web.naver.jp/app/ebiz_rules/ja/
URL_SAFETY_GUIDE=http://line-web.naver.jp/app/safety/ja/
VOIP_LOG_SERVER_URL=http://log1-amp.line-apps.com/log
URL_AUTH_AGE_CALLBACK=https?://agecheck[.]line[.]me(:[0-9]*)?/callback/.*
URL_AUTH_AGE_LOGIN=https?://agecheck[.]line[.]me(:[0-9]*)?/docomo/login.*
URL_CHINA_BAD_WORDS_INFO=http://line.naver.jp/app/resources/bwi
URL_CHINA_BAD_WORDS=https://line.naver.jp/app/resources/bwraw
URL_LINE_AT=line://ch/1360731415
URL_POKER=poker.line.naver.jp
CH_ID_REWARD_COIN=1370466387
imageLoggerLever=OFF