rules:
- id: android-keystore-keygenparameterspec-builder-config
  languages:
  - java
  message: The `KeyGenParameterSpec.Builder` must include proper configurations such
    as block modes (e.g., CBC) and encryption paddings (e.g., PKCS7Padding).
  pattern-not-inside: "$CLASS {\n    $METHOD {\n        $BLOCK_MODES.contains(\"CBC\"\
    ) && $ENCRYPTION_PADDINGS.contains(\"PKCS7Padding\");\n    }\n}\n"
  patterns:
  - pattern: "new KeyGenParameterSpec.Builder($KEY_ALIAS, $PURPOSE)\n    .setBlockModes($BLOCK_MODES)\n\
      \    .setEncryptionPaddings($ENCRYPTION_PADDINGS)\n"
  severity: ERROR
