rules:
- id: android-cleartext-traffic-permitted-base-config
  languages:
    - xml
  message: Cleartext traffic is permitted in the base configuration. Consider setting cleartextTrafficPermitted to false.
  metadata:
    cwe: CWE-319
    owasp: A6-Security Misconfiguration
  patterns:
    - pattern: |
        <network-security-config>
          ...
          <base-config cleartextTrafficPermitted="true">
            ...
          </base-config>
          ...
        </network-security-config>
  severity: ERROR
  options:
    # Prevent ellipses from matching multiple lines
    generic_ellipsis_max_span: 0

- id: android-cleartext-traffic-permitted-autofix
  languages:
    - xml
  message: Cleartext traffic is permitted. Consider setting cleartextTrafficPermitted to false.
  metadata:
    cwe: CWE-319
    owasp: A6-Security Misconfiguration
  patterns:
    - pattern: |
        cleartextTrafficPermitted="true"
  severity: ERROR
  fix: |
    cleartextTrafficPermitted="false"