rules:
- condition: all
  id: content-provider-security
  languages:
  - xml
  message: Ensure Content Providers are properly secured with permissions and are
    not unintentionally exported.
  metadata:
    area: content-providers
    authors:
    - Security Expert
    category: security
    references:
    - https://developer.android.com/guide/topics/providers/content-provider-basics
  paths:
    include:
    - '**/AndroidManifest.xml'
  patterns:
  - pattern: "<provider\n  android:name=\"$NAME\"\n  ... />\n"
  - pattern-not: "<provider\n  android:name=\"$NAME\"\n  android:exported=\"false\"\
      \n  ... />\n"
  - pattern-not: "<provider\n  android:name=\"$NAME\"\n  android:permission=\"signatureOrSystem\"\
      \n  ... />\n"
  - pattern-not: "<provider\n  android:name=\"$NAME\"\n  android:permission=\"signature\"\
      \n  ... />\n"
  - pattern-not: "<provider\n  android:name=\"$NAME\"\n  android:permission=\"privileged\"\
      \n  ... />\n"
  - pattern-not: "<provider\n  android:name=\"$NAME\"\n  android:permission=\"signature|privileged\"\
      \n  ... />\n"
  - pattern-not: "<provider\n  android:name=\"$NAME\"\n  android:permission=\"privileged|signature\"\
      \n  ... />\n"
  severity: ERROR
