rules:
- id: android-applicationexitinfo-api
  languages:
  - java
  message: The app uses the ApplicationExitInfo API, which may access user data related to app info and performance. Ensure it is not used to handle sensitive user data insecurely.
  metadata:
    category: Android Security
    technology: Android
  severity: ERROR
  patterns:
  - pattern: |
      ApplicationExitInfo $X = $Y;
  - pattern-either:
    - pattern: |
        $X.getReason();
    - pattern: |
        $X.getTimestamp();
    - pattern: |
        $X.getProcessName();
  - pattern-not: |
      $X = null;
  - pattern-not: |
      // Ensure no sensitive data is logged or exposed
      System.out.println($X);